import React from 'react'

const Faq = () => {
  return (
    <div className="font-abc text-gray-700 mb-20">
      <div>
        <h1 className="text-center text-6xl font-bold p-5">FAQ</h1>
        <p className="text-center text-2xl font-semibold pb-10">
          Frequently Asked Questions
        </p>
      </div>
      <div className="">
        <div className="collapse collapse-arrow bg-gray-700 text-gray-300 rounded-none">
          <input type="radio" name="my-accordion-2" defaultChecked />
          <div className="collapse-title text-xl font-medium">
            What is a URL shortener?
          </div>
          <div className="collapse-content">
            <p>hello</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-gray-700 text-gray-300 rounded-none">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">
            How do i use your URL shortener?
          </div>
          <div className="collapse-content">
            <p>hello</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-gray-700 text-gray-300 rounded-none">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">
            Can i customise my short links?
          </div>
          <div className="collapse-content">
            <p>hello</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-gray-700 text-gray-300 rounded-none">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">
            Is there a limit to the number of links i can shorten?
          </div>
          <div className="collapse-content">
            <p>hello</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-gray-700 text-gray-300 rounded-none">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">
            How long are the short links generated by your platform?
          </div>
          <div className="collapse-content">
            <p>hello</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Faq